### ISSUE TITLE
Reverse Backup - Mnemonic to bitbox seed backup format

### ISSUE THREAD

**Issue by wysi** [digitalbitbox/html_backup#12]
Thank for providing this offline backup decoding script.

Is there a script available for the vice versa: Entering a seed on an offline computer, generating the backup file, to be moved to an sd-card to setup a bitbox wallet?

The current maintainers of the repo are @benma and @douglasbakkum.

**Comment by benma** [comment]
There is no such script or tool. Note that the BitBox01 is no longer being produced or maintained, and you should look into migrating to a BitBox02 as soon as possible.

See https://shiftcrypto.support/help/en-us/16-bitbox01/143-bitbox01-end-of-sale-life-faqs

**Comment by wysi** [comment]
Thank you for the fast response - I got this repo wrong - I have a BitBox02, and tried to recover my seed from the SD card - this seems not to work with this repo (as it wants 64 Chars as Backup Input).  It seems only compatible with BitBox01


However, no issu, I can export my seed from the wallet display manually (by writing down the words from the wallet display)

**Comment by benma** [comment]
There is another tool for the BitBox02: https://github.com/digitalbitbox/bitbox02-backup-recovery

But it should only be used as a last resort. It is much safer to use the BitBox02 itself to create and restore backups.

**Comment by wysi** [comment]
Thank you for the hint!

Of course, would use it only on a always offline computer on a live system (without storage)
