### ISSUE TITLE
How I lost access to all my funds

### ISSUE THREAD

**Issue by i3uRi** [digitalbitbox/html_backup#3]
Hi, everyone! I hope you are all well.

I'm facing an issue with my Bitbox wallet and I would want to share it here and potentially to start to investigate whether my assumption is correct or not.  As we speak, I don't have access anymore to my funds. What I'm facing now could happen to anyone, therefore I kindly ask Bitbox Team to take full responsibility and help me solve this issue. 

Allow me first to give you a bit of background about the issue I'm facing and the steps that brought me here:

1. My Bitbox wallet went suddenly into reset mode after I tried for 3 times to access My Ether Wallet. I was accessing MEW without the Desktop App opened. Take into account that the normal process allows you to add for 15 times a wrong password. Worth mention that the password used was the same password used 4 days prior to this event to transfer funds. I'm 100% sure since I have double backups on all my passwords.

2. Since my Bitbox went into reset mode, I had to initiate a new wallet.
3. I restored the previous one in order to regain access to my funds. I used the same password which has double backups.
4. I accessed MEW and I was surprised to see a new list of addresses. The address that I was looking for was not there anymore.
5. I opened the backup center on my laptop and tried to obtain the private key, but no luck. None of the keys were the right one. Bear in mind that I used the same password.

**Assumption 1:** As it looks, it seems that the password might be wrong, but I totally disagree with his scenario since I have double backups for this password made 3 weeks ago. I'm over 100% sure that both the password and the wallet backup from pdf file are the ones configured at the initialization of the wallet. Since then I have used the same password without any issue for in and out my funds from my Bitbox. **More concrete, I have a backup of my password with the following timestamp Jan 23, 2018, 1:45:56 PM and since then 9 outbound transactions recorded on Etherscan.** That's crystal clear.

**Assumption 2:** I have two special characters within my password, namely ~ and / This made me think whether is something wrong with two potential password fields as follow:

- The one from Desktop App that is used when an user wants to restore a wallet
![bitbox desktop app password field](https://user-images.githubusercontent.com/27950955/36089081-c459ecc8-0fe2-11e8-841e-342ba91ae0de.png)

- And the one from Backup Center that is used when an user wants to have the private keys displayed
![bitbox backup center password field](https://user-images.githubusercontent.com/27950955/36089092-cc61ad7a-0fe2-11e8-8c68-9f78238b6d0c.png)

Guys, this issue freaked me out. I do understand that from support the only thing that seems to be wrong is the password, but I strongly disagree. I have backups very well documented and dated. **Could you please investigate my assumption, that special characters might not be allowed on those two fields and potentially this might generate a totally different list of private keys and addresses?**

_Please find below INs and OUTs proof from the address that I have lost control. Bear in mind that I used the same password to access my address or funds. Therefore the reset of the Bitbox was not triggered by a known use-case and neither the theory that my password is wrong doesn't stand. This is frustrating as hell._

![ins and outs proof](https://user-images.githubusercontent.com/27950955/36089269-b0f77604-0fe3-11e8-8929-107c5d45de8f.png)

Much appreciated,
Adrian I.

**Comment by i3uRi** [comment]
**Assumption 3:** Just wonder whether I landed in an edge case and something went wrong with my pdf wallet backup from the beginning. I'm saying that because I didn't check if this pdf file is accurate or not. And I don't know how either. I'm using it as it is since the wallet initialization. Since I have a backup of the password made on 23rd of January and till the reset I made a few transactions, I might assume this worse case scenario as well. What do you think?

**Comment by i3uRi** [comment]
Just a quick update to have the full big picture: 

I'm using a Surface Pro 4 which has Windows10 and I have accessed Center Backup with Chrome 64.0.3282.140 (Official Build) (64-bit) and Firefox 58.0.2 (64-bit). No luck so far. :|

**Comment by douglasbakkum** [comment]
Closing as conversation had continued offline.
